services:
  postgres:
    image: postgres:15
    container_name: weather_postgres
    restart: always
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL:
        jdbc:postgresql://postgres:5432/weather_db
      SPRING_DATASOURCE_USERNAME:
        postgres
      SPRING_DATASOURCE_PASSWORD: 1234