services:
  postgres:
    image: postgres:15
    container_name: weather_postgres
    restart: always
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"