
ALTER TABLE users ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE locations ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE locations ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sessions ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sessions ADD COLUMN updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE FUNCTION update_updated_column()
RETURNS TRIGGER AS $$
BEGIN
NEW.updated = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER trg_updated_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_column();

CREATE TRIGGER trg_updated_locations
BEFORE UPDATE ON locations
FOR EACH ROW
EXECUTE FUNCTION update_updated_column();

CREATE TRIGGER trg_updated_sessions
    BEFORE UPDATE ON sessions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_column();
